development:
  session_expire: 1
  gmail_username: 'global@telsoft.com.vn'
  gmail_password: 'tlsglobal123'
  server_smtp: 'smtp.gmail.com'
  amazon_tag: 'cu0f0-20'
test:
  session_expire: 1
  gmail_username: 'global@telsoft.com.vn'
  gmail_password: 'tlsglobal123'
  server_smtp: 'smtp.gmail.com'
  amazon_tag: 'cu0f0-20'
production:
  session_expire: 1
  gmail_username: 'global@telsoft.com.vn'
  gmail_password: 'tlsglobal123'
  server_smtp: 'smtp.gmail.com'
  amazon_tag: 'cu0f0-20'